Matlab Examples
ome/bio-formats-examples pull request #127
Opened 2024-04-09 14:45 UTC by jburel

This PR is built on top of #126 to avoid conflicts.

This PR allows to run the matlab examples on MacOS and Ubuntu using the bf-octave docker image
It takes longer to run the test on Mac since docker needs to be installed.
I can close #126 if we prefer to combine everything in one PR

2024-04-09 15:13 UTC, sbesson reviewed
Should that be a completely separate workflow? There is no relationship to the Java source code and/or the Maven/Ant build system so introducing this as tasks is a bit artificial.

Also, there is no real reason to run these tests for each JDK version since only the JDK of the Docker image should matter

2024-04-09 15:32 UTC, jburel commented
I was thinking to add a new workflow. I put there for convenience for initial review
I will put it in its own workflow

2024-04-10 13:16 UTC, jburel commented
@sbesson matlab tests now run in separate workflow.

2024-04-10 13:37 UTC, sbesson commented
```
warning: function ./test.m shadows a core library function
error: no such file, '/home/octave/src/main/matlab/bftest.m'
error: source: error sourcing file '/home/octave/src/main/matlab/bftest.m'
```

2024-04-10 14:00 UTC, jburel commented
Thanks. I think we have again a similar problem I had on the octave repo with false positive

2024-04-10 16:00 UTC, sbesson requested changes
Still running into runtime failures

```
warning: function ./test.m shadows a core library function
error: 'bfCheckJavaPath' undefined near line 1 column 1
error: called from
    /src/main/matlab/bftest.m at line 1 column 1
```

> Thanks. I think we have again a similar problem I had on the octave repo with false positive

Yes the inability to get a failed status above is not great. Going one step further, this makes me consider whether it is valuable to invest in this work at all if we are unable to flag failures as this defies the point of these workflows in the first place. I don't know if the issue lies with GNU Octave, the Docker infrastructure or the way the file is executed.

2024-04-10 16:03 UTC, jburel commented
I will have to check 
Anyway i have now adjusted the work. The failure is now expected (but still green)

2024-09-16 13:23 UTC, closed without merging