Add macro examples from OME 2020 NGFF workshop
ome/bio-formats-examples pull request #69
Opened 2020-05-28 10:54 UTC by dgault

Adding 3 new python macro examples and a groovy example. 

This have been created for the OME 2020 workshop on next gen file formats. The goal of them is to show how to use tiled and pyramidal conversions to allow large plane (>2GB) images to be opened within the ImageJ environment.

The ImageJ Macro and plugins examples have typically lived in the `bio-formats_plugins/utils` folder. It would be good to start building a larger range of macro scripting examples in the 

The one major outstanding issue with creating examples here is the ongoing testing implications for these macros.

2024-04-09 11:06 UTC, jburel requested changes
Due to the support of Jython in Fiji, we rewrote all our omero training scripts in groovy
Only one script is in groovy. It might be better to only add groovy scripts

2024-04-09 11:06 UTC, jburel commented on src/main/macros/jython/PyramidConversion.py
> +file = "/path/to/inputFile.tiff"
file = IJ.getFilePath("Choose a Tiff File")
if file is None:
print("cancel")
sys.exit(2)

path = ('.').join(file.split('.')[:-1])
outFile = path + ".ome.tiff"

2024-04-09 11:06 UTC, jburel commented on src/main/macros/jython/PyramidConversion.py
> +from ij import IJ
```suggestion
from ij import IJ
import sys
```

2024-04-09 11:06 UTC, jburel commented on src/main/macros/jython/PyramidConversion.py
> +reader.close()
```suggestion
reader.close()
IJ.log("Done")

```

2024-04-09 11:06 UTC, jburel commented on src/main/macros/jython/TiledConversion.py
> +import math
```suggestion
import math
import sys
```

2024-04-09 11:06 UTC, jburel commented on src/main/macros/jython/TiledConversion.py
> +file = "/path/to/inputFile.tiff"
```
file = IJ.getFilePath("Choose a Tiff File")
if file is None:
   print("cancel")
   sys.exit(2)

path = ('.').join(file.split('.')[:-1])
outFile = path + ".ome.tiff"
```

2024-04-09 11:06 UTC, jburel commented on src/main/macros/jython/TiledConversion.py
> +IJ.log("Done")
```suggestion
IJ.log("Done")

```

2025-01-13 15:37 UTC, melissalinkert commented
Closing, as discussed with the formats team earlier today.

2025-01-13 15:37 UTC, closed without merging